<div class="footer">
    <div class="footer-images"><img src="<?php echo e(asset('assets/images/new-design/images/logo.png')); ?>" loading="lazy" sizes="(max-width: 479px) 67vw, 114px" srcset="<?php echo e(asset('assets/images/new-design/images/logo-p-500.png')); ?> 500w, <?php echo e(asset('assets/images/new-design/images/logo-p-800.png')); ?> 800w, <?php echo e(asset('assets/images/new-design/images/logo-p-1080.png')); ?> 1080w, <?php echo e(asset('assets/images/new-design/images/logo-p-1600.png')); ?> 1600w, <?php echo e(asset('assets/images/new-design/images/logo-p-2000.png')); ?> 2000w, <?php echo e(asset('assets/images/new-design/images/logo-p-2600.png')); ?> 2600w, <?php echo e(asset('assets/images/new-design/images/logo.png 2893w')); ?>" alt="" class="footer-logo">
        <div class="footer-certificates"><img src="<?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao.png')); ?>" loading="lazy" sizes="(max-width: 479px) 39vw, 124px" srcset="<?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao-p-500.png')); ?> 500w, <?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao-p-800.png')); ?> 800w, <?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao-p-1080.png')); ?> 1080w, <?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao-p-1600.png')); ?> 1600w, <?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao-p-2000.png')); ?> 2000w, <?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao-p-2600.png')); ?> 2600w, <?php echo e(asset('assets/images/new-design/images/gc_gaming-curacao.png 2893w')); ?>" alt="" class="curacao"><img src="<?php echo e(asset('assets/images/new-design/images/18.png')); ?>" loading="lazy" alt="" class="age"></div>
    </div>
    <div class="footer-description">
        <div class="footer-description-text"><strong>coroabet.online</strong> é dedicada a oferecer a melhor experiência aos jogadores. Experimente! Divirta-se jogando e conquiste vitórias!</div>
        <div class="footer-rights">©2024 coroabet.online - Todos os direitos reservados.</div>
    </div>
</div>

<?php /**PATH /home/hasan/Desktop/real pro/coroabet/resources/views/includes/footer.blade.php ENDPATH**/ ?>